import type { ResumeDocumentV1 } from './types';

export function emptyResume(): ResumeDocumentV1 {
  return {
    v: 1,
    fullName: '',
    headline: '',
    summary: '',
    social: {
      linkedin: '',
      github: '',
      portfolio: '',
      twitter: '',
      other: '',
    },
    experience: [],
    education: [],
    projects: [],
    certifications: [],
    languages: [],
    skillGroups: [],
    customSections: [],
    visibility: {
      headline: true,
      summary: true,
      experience: true,
      education: true,
      projects: true,
      certifications: true,
      languages: true,
      skills: true,
      custom: true,
      profileDetails: true,
      achievements: true,
      social: true,
    },
    layout: {
      template: 'classic',
      density: 'comfortable',
      showPageBreakHints: false,
      accentColor: '#0f172a',
      showPageNumbersInPdf: true,
      headerStyle: 'centered',
      ruleStyle: 'accent',
      pdfTypography: 'standard',
      pageSize: 'A4',
      marginMm: { top: 0, right: 0, bottom: 0, left: 0 },
      contentPaddingMm: 10,
      sectionGapScale: 1,
      lineHeightScale: 1.35,
      pdfFontFamily: 'Helvetica',
      fontScale: 1,
      bodyTextAlign: 'left',
      headerTextAlign: 'center',
      sectionTitleAlign: 'left',
    },
  };
}
