/**
 * Stay & Meals - Data
 *
 * Comprehensive accommodation information.
 */

import type { Room, Availability } from '../types';

export const stayData: {
  rooms: Room[];
  availability: Availability[];
} = {
  rooms: [
    {
      id: 'shared-room',
      name: 'Shared Room',
      type: 'shared',
      description: 'Comfortable shared accommodation with 2-4 beds per room. Clean, well-maintained rooms with attached bathrooms. Perfect for individual travelers and small groups.',
      timings: {
        monday: { open: '00:00', close: '23:59' },
        tuesday: { open: '00:00', close: '23:59' },
        wednesday: { open: '00:00', close: '23:59' },
        thursday: { open: '00:00', close: '23:59' },
        friday: { open: '00:00', close: '23:59' },
        saturday: { open: '00:00', close: '23:59' },
        sunday: { open: '00:00', close: '23:59' },
      },
      status: 'open',
      capacity: 500,
      maxGuests: 4,
      amenities: [
        'Attached bathroom',
        '24/7 hot water',
        'Bedding provided',
        'Room cleaning service',
        'Wi-Fi access',
        'Fan/AC',
      ],
      pricing: [
        {
          id: 'shared-basic',
          name: 'Basic Contribution',
          contribution: 500,
          currency: 'INR',
          description: 'Per person per night',
          conditions: ['Includes accommodation only'],
        },
        {
          id: 'shared-meals',
          name: 'With Meals',
          contribution: 1200,
          currency: 'INR',
          description: 'Per person per night',
          conditions: ['Includes accommodation + 3 meals daily'],
        },
      ],
      images: ['/images/accommodation/shared-room-1.jpg', '/images/accommodation/shared-room-2.jpg'],
      mealIncluded: false,
      eligibility: {
        familyFriendly: true,
        specialNeeds: true,
      },
      location: {
        name: 'Accommodation Block A',
        building: 'Residential Complex',
        floor: 'Ground & First Floor',
      },
      contact: {
        phone: '+91-80-2843-2100',
        extension: '401',
      },
      rules: [
        'Check-in: 2:00 PM | Check-out: 11:00 AM',
        'Advance booking recommended',
        'Respectful behavior expected',
        'Quiet hours: 10:00 PM - 6:00 AM',
        'No smoking or alcohol',
        'Visitors must register at reception',
      ],
    },
    {
      id: 'private-room',
      name: 'Private Room',
      type: 'private',
      description: 'Private single or double occupancy rooms with attached bathrooms. More privacy and comfort for individuals or couples. All basic amenities included.',
      timings: {
        monday: { open: '00:00', close: '23:59' },
        tuesday: { open: '00:00', close: '23:59' },
        wednesday: { open: '00:00', close: '23:59' },
        thursday: { open: '00:00', close: '23:59' },
        friday: { open: '00:00', close: '23:59' },
        saturday: { open: '00:00', close: '23:59' },
        sunday: { open: '00:00', close: '23:59' },
      },
      status: 'open',
      capacity: 200,
      maxGuests: 2,
      amenities: [
        'Private room',
        'Attached bathroom',
        '24/7 hot water',
        'Bedding provided',
        'Room service',
        'Wi-Fi access',
        'AC/Fan',
        'Study table',
      ],
      pricing: [
        {
          id: 'private-basic',
          name: 'Basic Contribution',
          contribution: 1500,
          currency: 'INR',
          description: 'Per room per night',
          conditions: ['Single or double occupancy', 'Includes accommodation only'],
        },
        {
          id: 'private-meals',
          name: 'With Meals',
          contribution: 2500,
          currency: 'INR',
          description: 'Per room per night',
          conditions: ['Single or double occupancy', 'Includes accommodation + 3 meals daily'],
        },
      ],
      images: ['/images/accommodation/private-room-1.jpg'],
      mealIncluded: false,
      eligibility: {
        familyFriendly: true,
        specialNeeds: true,
      },
      location: {
        name: 'Accommodation Block B',
        building: 'Residential Complex',
        floor: 'All Floors',
      },
      contact: {
        phone: '+91-80-2843-2100',
        extension: '402',
      },
      rules: [
        'Check-in: 2:00 PM | Check-out: 11:00 AM',
        'Advance booking required',
        'Maximum 2 guests per room',
        'Respectful behavior expected',
        'Quiet hours: 10:00 PM - 6:00 AM',
      ],
    },
    {
      id: 'dormitory',
      name: 'Dormitory',
      type: 'dormitory',
      description: 'Large shared dormitory spaces with multiple beds. Economical option for groups and individuals. Clean facilities with common bathrooms.',
      timings: {
        monday: { open: '00:00', close: '23:59' },
        tuesday: { open: '00:00', close: '23:59' },
        wednesday: { open: '00:00', close: '23:59' },
        thursday: { open: '00:00', close: '23:59' },
        friday: { open: '00:00', close: '23:59' },
        saturday: { open: '00:00', close: '23:59' },
        sunday: { open: '00:00', close: '23:59' },
      },
      status: 'open',
      capacity: 800,
      maxGuests: 1,
      amenities: [
        'Shared dormitory',
        'Common bathrooms',
        '24/7 hot water',
        'Bedding provided',
        'Lockers available',
        'Wi-Fi access',
        'Fan',
      ],
      pricing: [
        {
          id: 'dorm-basic',
          name: 'Basic Contribution',
          contribution: 300,
          currency: 'INR',
          description: 'Per person per night',
          conditions: ['Includes accommodation only'],
        },
        {
          id: 'dorm-meals',
          name: 'With Meals',
          contribution: 900,
          currency: 'INR',
          description: 'Per person per night',
          conditions: ['Includes accommodation + 3 meals daily'],
        },
      ],
      images: ['/images/accommodation/dormitory-1.jpg'],
      mealIncluded: false,
      eligibility: {
        familyFriendly: false,
        specialNeeds: true,
      },
      location: {
        name: 'Dormitory Block',
        building: 'Residential Complex',
        floor: 'Ground Floor',
      },
      contact: {
        phone: '+91-80-2843-2100',
        extension: '403',
      },
      rules: [
        'Check-in: 2:00 PM | Check-out: 11:00 AM',
        'Respectful behavior expected',
        'Quiet hours: 10:00 PM - 6:00 AM',
        'Lockers available for valuables',
        'No smoking or alcohol',
      ],
    },
    {
      id: 'family-room',
      name: 'Family Room',
      type: 'family',
      description: 'Spacious rooms designed for families with children. Multiple beds, attached bathroom, and family-friendly amenities. Perfect for families visiting together.',
      timings: {
        monday: { open: '00:00', close: '23:59' },
        tuesday: { open: '00:00', close: '23:59' },
        wednesday: { open: '00:00', close: '23:59' },
        thursday: { open: '00:00', close: '23:59' },
        friday: { open: '00:00', close: '23:59' },
        saturday: { open: '00:00', close: '23:59' },
        sunday: { open: '00:00', close: '23:59' },
      },
      status: 'open',
      capacity: 100,
      maxGuests: 6,
      amenities: [
        'Family-sized room',
        'Multiple beds',
        'Attached bathroom',
        '24/7 hot water',
        'Bedding provided',
        'Room service',
        'Wi-Fi access',
        'AC',
        'Extra space for children',
      ],
      pricing: [
        {
          id: 'family-basic',
          name: 'Basic Contribution',
          contribution: 2500,
          currency: 'INR',
          description: 'Per room per night',
          conditions: ['Up to 4 adults or 2 adults + children', 'Includes accommodation only'],
        },
        {
          id: 'family-meals',
          name: 'With Meals',
          contribution: 4000,
          currency: 'INR',
          description: 'Per room per night',
          conditions: ['Up to 4 adults or 2 adults + children', 'Includes accommodation + 3 meals daily'],
        },
      ],
      images: ['/images/accommodation/family-room-1.jpg'],
      mealIncluded: false,
      eligibility: {
        familyFriendly: true,
        specialNeeds: true,
      },
      location: {
        name: 'Family Accommodation Block',
        building: 'Residential Complex',
        floor: 'First & Second Floor',
      },
      contact: {
        phone: '+91-80-2843-2100',
        extension: '404',
      },
      rules: [
        'Check-in: 2:00 PM | Check-out: 11:00 AM',
        'Advance booking required',
        'Family-friendly environment',
        'Children must be supervised',
        'Respectful behavior expected',
      ],
    },
  ],

  availability: [
    // Sample availability data - in production, this would be dynamic
    {
      date: new Date().toISOString().split('T')[0],
      roomId: 'shared-room',
      available: 450,
      booked: 50,
      total: 500,
    },
    {
      date: new Date().toISOString().split('T')[0],
      roomId: 'private-room',
      available: 180,
      booked: 20,
      total: 200,
    },
  ],
};
