/**
 * Articles & Blogs - Data
 *
 * Content data for the Articles & Blogs page.
 * In production, this would be fetched from a CMS or database.
 */

import type { ArticlesPageData } from '../types';

export const articlesData: ArticlesPageData = {
  featured: [
    {
      id: 'article-1',
      title: 'The Science of Breath: How Pranayama Transforms Your Mind and Body',
      slug: 'science-of-breath-pranayama',
      excerpt: 'Discover the profound impact of conscious breathing on your physical health, mental clarity, and emotional well-being through ancient yogic wisdom and modern scientific research.',
      content: 'Full article content...',
      author: {
        id: 'author-1',
        name: 'Dr. Priya Sharma',
        bio: 'Yoga therapist and researcher specializing in breathwork',
        avatar: '/images/authors/priya-sharma.jpg',
        role: 'Senior Yoga Therapist',
      },
      readingTime: 8,
      category: {
        id: 'wellness',
        name: 'Wellness',
        slug: 'wellness',
        description: 'Articles on health and wellness',
        articleCount: 45,
        color: '#4A9B9A',
      },
      tags: [
        { id: 'tag-1', name: 'Pranayama', slug: 'pranayama', articleCount: 12 },
        { id: 'tag-2', name: 'Breathwork', slug: 'breathwork', articleCount: 8 },
        { id: 'tag-3', name: 'Science', slug: 'science', articleCount: 15 },
      ],
      featuredImage: '/images/articles/science-of-breath.jpg',
      publishedAt: '2025-01-15T10:00:00Z',
      createdAt: '2025-01-15T10:00:00Z',
      updatedAt: '2025-01-15T10:00:00Z',
      featured: true,
      viewCount: 1250,
    },
  ],

  categories: [
    { id: 'all', name: 'All Articles', slug: 'all', articleCount: 120 },
    { id: 'wisdom', name: 'Wisdom', slug: 'wisdom', description: 'Ancient wisdom and philosophy', articleCount: 35, color: '#C9A961' },
    { id: 'wellness', name: 'Wellness', slug: 'wellness', description: 'Health and wellness', articleCount: 45, color: '#4A9B9A' },
    { id: 'events', name: 'Events', slug: 'events', description: 'Event coverage and updates', articleCount: 20, color: '#B8A5D4' },
    { id: 'stories', name: 'Stories', slug: 'stories', description: 'Inspiring transformation stories', articleCount: 20, color: '#7B9E87' },
  ],

  tags: [
    { id: 'tag-1', name: 'Meditation', slug: 'meditation', articleCount: 25 },
    { id: 'tag-2', name: 'Yoga', slug: 'yoga', articleCount: 30 },
    { id: 'tag-3', name: 'Stress Relief', slug: 'stress-relief', articleCount: 18 },
    { id: 'tag-4', name: 'Mindfulness', slug: 'mindfulness', articleCount: 22 },
    { id: 'tag-5', name: 'Pranayama', slug: 'pranayama', articleCount: 12 },
    { id: 'tag-6', name: 'Wellness', slug: 'wellness', articleCount: 15 },
    { id: 'tag-7', name: 'Transformation', slug: 'transformation', articleCount: 20 },
    { id: 'tag-8', name: 'Wisdom', slug: 'wisdom', articleCount: 28 },
  ],

  articles: [
    {
      id: 'article-1',
      title: 'The Science of Breath: How Pranayama Transforms Your Mind and Body',
      slug: 'science-of-breath-pranayama',
      excerpt: 'Discover the profound impact of conscious breathing on your physical health, mental clarity, and emotional well-being.',
      content: 'Full article content...',
      author: {
        id: 'author-1',
        name: 'Dr. Priya Sharma',
        bio: 'Yoga therapist and researcher',
        avatar: '/images/authors/priya-sharma.jpg',
        role: 'Senior Yoga Therapist',
      },
      readingTime: 8,
      category: {
        id: 'wellness',
        name: 'Wellness',
        slug: 'wellness',
        articleCount: 45,
      },
      tags: [
        { id: 'tag-1', name: 'Pranayama', slug: 'pranayama', articleCount: 12 },
        { id: 'tag-2', name: 'Breathwork', slug: 'breathwork', articleCount: 8 },
      ],
      featuredImage: '/images/articles/science-of-breath.jpg',
      publishedAt: '2025-01-15T10:00:00Z',
      createdAt: '2025-01-15T10:00:00Z',
      updatedAt: '2025-01-15T10:00:00Z',
      featured: true,
      viewCount: 1250,
    },
    {
      id: 'article-2',
      title: 'Finding Inner Peace in a Busy World',
      slug: 'inner-peace-busy-world',
      excerpt: 'Practical techniques to maintain calm and centeredness amidst the chaos of modern life.',
      content: 'Full article content...',
      author: {
        id: 'author-2',
        name: 'Rajesh Kumar',
        bio: 'Meditation teacher and life coach',
        avatar: '/images/authors/rajesh-kumar.jpg',
        role: 'Senior Meditation Teacher',
      },
      readingTime: 6,
      category: {
        id: 'wisdom',
        name: 'Wisdom',
        slug: 'wisdom',
        articleCount: 35,
      },
      tags: [
        { id: 'tag-3', name: 'Stress Relief', slug: 'stress-relief', articleCount: 18 },
        { id: 'tag-4', name: 'Mindfulness', slug: 'mindfulness', articleCount: 22 },
      ],
      featuredImage: '/images/articles/inner-peace.jpg',
      publishedAt: '2025-01-10T10:00:00Z',
      createdAt: '2025-01-10T10:00:00Z',
      updatedAt: '2025-01-10T10:00:00Z',
      viewCount: 980,
    },
    {
      id: 'article-3',
      title: 'The Art of Living: A Journey of Transformation',
      slug: 'art-of-living-journey',
      excerpt: 'Stories of transformation from participants who discovered new meaning and purpose through our programs.',
      content: 'Full article content...',
      author: {
        id: 'author-3',
        name: 'Sarah Johnson',
        bio: 'Writer and transformation coach',
        avatar: '/images/authors/sarah-johnson.jpg',
        role: 'Content Writer',
      },
      readingTime: 10,
      category: {
        id: 'stories',
        name: 'Stories',
        slug: 'stories',
        articleCount: 20,
      },
      tags: [
        { id: 'tag-7', name: 'Transformation', slug: 'transformation', articleCount: 20 },
        { id: 'tag-8', name: 'Wisdom', slug: 'wisdom', articleCount: 28 },
      ],
      featuredImage: '/images/articles/transformation.jpg',
      publishedAt: '2025-01-05T10:00:00Z',
      createdAt: '2025-01-05T10:00:00Z',
      updatedAt: '2025-01-05T10:00:00Z',
      viewCount: 750,
    },
    {
      id: 'article-4',
      title: 'Yoga for Stress Management: A Complete Guide',
      slug: 'yoga-stress-management',
      excerpt: 'Learn how specific yoga poses and breathing techniques can help you manage stress effectively.',
      content: 'Full article content...',
      author: {
        id: 'author-1',
        name: 'Dr. Priya Sharma',
        bio: 'Yoga therapist and researcher',
        avatar: '/images/authors/priya-sharma.jpg',
        role: 'Senior Yoga Therapist',
      },
      readingTime: 7,
      category: {
        id: 'wellness',
        name: 'Wellness',
        slug: 'wellness',
        articleCount: 45,
      },
      tags: [
        { id: 'tag-2', name: 'Yoga', slug: 'yoga', articleCount: 30 },
        { id: 'tag-3', name: 'Stress Relief', slug: 'stress-relief', articleCount: 18 },
      ],
      featuredImage: '/images/articles/yoga-stress.jpg',
      publishedAt: '2024-12-28T10:00:00Z',
      createdAt: '2024-12-28T10:00:00Z',
      updatedAt: '2024-12-28T10:00:00Z',
      viewCount: 1100,
    },
    {
      id: 'article-5',
      title: 'Maha Shivratri 2026: A Night of Deep Meditation',
      slug: 'maha-shivratri-2026',
      excerpt: 'Join millions worldwide in celebrating this auspicious night of meditation and transformation.',
      content: 'Full article content...',
      author: {
        id: 'author-4',
        name: 'Event Team',
        bio: 'Art of Living event coordinators',
        avatar: '/images/authors/event-team.jpg',
        role: 'Event Coordinator',
      },
      readingTime: 5,
      category: {
        id: 'events',
        name: 'Events',
        slug: 'events',
        articleCount: 20,
      },
      tags: [
        { id: 'tag-1', name: 'Meditation', slug: 'meditation', articleCount: 25 },
        { id: 'tag-8', name: 'Wisdom', slug: 'wisdom', articleCount: 28 },
      ],
      featuredImage: '/images/articles/shivratri-2026.jpg',
      publishedAt: '2024-12-20T10:00:00Z',
      createdAt: '2024-12-20T10:00:00Z',
      updatedAt: '2024-12-20T10:00:00Z',
      viewCount: 2100,
    },
    {
      id: 'article-6',
      title: 'Understanding the Mind-Body Connection',
      slug: 'mind-body-connection',
      excerpt: 'Explore how our thoughts, emotions, and physical health are deeply interconnected.',
      content: 'Full article content...',
      author: {
        id: 'author-2',
        name: 'Rajesh Kumar',
        bio: 'Meditation teacher and life coach',
        avatar: '/images/authors/rajesh-kumar.jpg',
        role: 'Senior Meditation Teacher',
      },
      readingTime: 9,
      category: {
        id: 'wisdom',
        name: 'Wisdom',
        slug: 'wisdom',
        articleCount: 35,
      },
      tags: [
        { id: 'tag-4', name: 'Mindfulness', slug: 'mindfulness', articleCount: 22 },
        { id: 'tag-6', name: 'Wellness', slug: 'wellness', articleCount: 15 },
      ],
      featuredImage: '/images/articles/mind-body.jpg',
      publishedAt: '2024-12-15T10:00:00Z',
      createdAt: '2024-12-15T10:00:00Z',
      updatedAt: '2024-12-15T10:00:00Z',
      viewCount: 890,
    },
  ],

  authors: [
    {
      id: 'author-1',
      name: 'Dr. Priya Sharma',
      bio: 'Yoga therapist and researcher specializing in breathwork and stress management',
      avatar: '/images/authors/priya-sharma.jpg',
      role: 'Senior Yoga Therapist',
    },
    {
      id: 'author-2',
      name: 'Rajesh Kumar',
      bio: 'Meditation teacher and life coach with 20+ years of experience',
      avatar: '/images/authors/rajesh-kumar.jpg',
      role: 'Senior Meditation Teacher',
    },
    {
      id: 'author-3',
      name: 'Sarah Johnson',
      bio: 'Writer and transformation coach sharing inspiring stories',
      avatar: '/images/authors/sarah-johnson.jpg',
      role: 'Content Writer',
    },
  ],
};
