/**
 * Videos & Talks - Data
 *
 * Content data for the Videos & Talks page.
 */

import type { VideosPageData } from '../types';

export const videosData: VideosPageData = {
  featured: [
    {
      id: 'video-1',
      title: 'The Art of Living: A Journey Within',
      slug: 'art-of-living-journey-within',
      description: 'An inspiring talk on finding inner peace and purpose in life through meditation and self-discovery.',
      url: 'https://www.youtube.com/watch?v=example1',
      thumbnail: '/images/videos/featured-1.jpg',
      duration: 3240, // 54 minutes in seconds
      speaker: {
        id: 'speaker-1',
        name: 'Gurudev Sri Sri Ravi Shankar',
        bio: 'Founder of Art of Living Foundation',
        avatar: '/images/speakers/gurudev.jpg',
        role: 'Spiritual Leader',
      },
      category: {
        id: 'wisdom',
        name: 'Wisdom',
        slug: 'wisdom',
        description: 'Wisdom talks and discourses',
        videoCount: 45,
        icon: 'BookOpen',
      },
      views: 1250000,
      transcript: 'Full transcript available...',
      publishedAt: '2025-01-10T10:00:00Z',
      createdAt: '2025-01-10T10:00:00Z',
      updatedAt: '2025-01-10T10:00:00Z',
      featured: true,
      language: 'English',
    },
  ],

  categories: [
    { id: 'all', name: 'All Videos', slug: 'all', videoCount: 250 },
    { id: 'wisdom', name: 'Wisdom', slug: 'wisdom', description: 'Wisdom talks and discourses', videoCount: 45, icon: 'BookOpen' },
    { id: 'meditation', name: 'Meditation', slug: 'meditation', description: 'Meditation guidance and practices', videoCount: 60, icon: 'Brain' },
    { id: 'talks', name: 'Talks', slug: 'talks', description: 'Inspirational talks and lectures', videoCount: 80, icon: 'Mic' },
    { id: 'events', name: 'Events', slug: 'events', description: 'Event recordings and highlights', videoCount: 65, icon: 'Calendar' },
  ],

  videos: [
    {
      id: 'video-1',
      title: 'The Art of Living: A Journey Within',
      slug: 'art-of-living-journey-within',
      description: 'An inspiring talk on finding inner peace and purpose in life.',
      url: 'https://www.youtube.com/watch?v=example1',
      thumbnail: '/images/videos/video-1.jpg',
      duration: 3240,
      speaker: {
        id: 'speaker-1',
        name: 'Gurudev Sri Sri Ravi Shankar',
        bio: 'Founder of Art of Living Foundation',
        avatar: '/images/speakers/gurudev.jpg',
        role: 'Spiritual Leader',
      },
      category: {
        id: 'wisdom',
        name: 'Wisdom',
        slug: 'wisdom',
        videoCount: 45,
      },
      views: 1250000,
      transcript: 'Full transcript...',
      publishedAt: '2025-01-10T10:00:00Z',
      createdAt: '2025-01-10T10:00:00Z',
      updatedAt: '2025-01-10T10:00:00Z',
      featured: true,
      language: 'English',
    },
    {
      id: 'video-2',
      title: 'Guided Meditation for Stress Relief',
      slug: 'guided-meditation-stress-relief',
      description: 'A 20-minute guided meditation session to help you release stress and find calm.',
      url: 'https://www.youtube.com/watch?v=example2',
      thumbnail: '/images/videos/video-2.jpg',
      duration: 1200,
      speaker: {
        id: 'speaker-2',
        name: 'Dr. Priya Sharma',
        bio: 'Senior Meditation Teacher',
        avatar: '/images/speakers/priya-sharma.jpg',
        role: 'Meditation Teacher',
      },
      category: {
        id: 'meditation',
        name: 'Meditation',
        slug: 'meditation',
        videoCount: 60,
      },
      views: 850000,
      publishedAt: '2025-01-08T10:00:00Z',
      createdAt: '2025-01-08T10:00:00Z',
      updatedAt: '2025-01-08T10:00:00Z',
      language: 'English',
    },
    {
      id: 'video-3',
      title: 'Maha Shivratri 2026 Celebration',
      slug: 'maha-shivratri-2026',
      description: 'Highlights from the global Maha Shivratri celebration with millions of participants.',
      url: 'https://www.youtube.com/watch?v=example3',
      thumbnail: '/images/videos/video-3.jpg',
      duration: 3600,
      speaker: {
        id: 'speaker-1',
        name: 'Gurudev Sri Sri Ravi Shankar',
        bio: 'Founder of Art of Living Foundation',
        avatar: '/images/speakers/gurudev.jpg',
        role: 'Spiritual Leader',
      },
      category: {
        id: 'events',
        name: 'Events',
        slug: 'events',
        videoCount: 65,
      },
      views: 2100000,
      publishedAt: '2025-01-05T10:00:00Z',
      createdAt: '2025-01-05T10:00:00Z',
      updatedAt: '2025-01-05T10:00:00Z',
      language: 'English',
    },
    {
      id: 'video-4',
      title: 'Understanding the Mind: A Practical Guide',
      slug: 'understanding-mind-practical-guide',
      description: 'Explore how the mind works and learn practical techniques to master your thoughts.',
      url: 'https://www.youtube.com/watch?v=example4',
      thumbnail: '/images/videos/video-4.jpg',
      duration: 2700,
      speaker: {
        id: 'speaker-3',
        name: 'Rajesh Kumar',
        bio: 'Senior Meditation Teacher',
        avatar: '/images/speakers/rajesh-kumar.jpg',
        role: 'Meditation Teacher',
      },
      category: {
        id: 'talks',
        name: 'Talks',
        slug: 'talks',
        videoCount: 80,
      },
      views: 650000,
      publishedAt: '2025-01-03T10:00:00Z',
      createdAt: '2025-01-03T10:00:00Z',
      updatedAt: '2025-01-03T10:00:00Z',
      language: 'English',
    },
    {
      id: 'video-5',
      title: 'Morning Meditation Practice',
      slug: 'morning-meditation-practice',
      description: 'Start your day with this energizing morning meditation practice.',
      url: 'https://www.youtube.com/watch?v=example5',
      thumbnail: '/images/videos/video-5.jpg',
      duration: 900,
      speaker: {
        id: 'speaker-2',
        name: 'Dr. Priya Sharma',
        bio: 'Senior Meditation Teacher',
        avatar: '/images/speakers/priya-sharma.jpg',
        role: 'Meditation Teacher',
      },
      category: {
        id: 'meditation',
        name: 'Meditation',
        slug: 'meditation',
        videoCount: 60,
      },
      views: 420000,
      publishedAt: '2024-12-28T10:00:00Z',
      createdAt: '2024-12-28T10:00:00Z',
      updatedAt: '2024-12-28T10:00:00Z',
      language: 'English',
    },
    {
      id: 'video-6',
      title: 'The Power of Breath: Pranayama Techniques',
      slug: 'power-of-breath-pranayama',
      description: 'Learn powerful breathing techniques that can transform your health and well-being.',
      url: 'https://www.youtube.com/watch?v=example6',
      thumbnail: '/images/videos/video-6.jpg',
      duration: 1800,
      speaker: {
        id: 'speaker-4',
        name: 'Yoga Master Ananda',
        bio: 'Senior Yoga Teacher',
        avatar: '/images/speakers/ananda.jpg',
        role: 'Yoga Teacher',
      },
      category: {
        id: 'wisdom',
        name: 'Wisdom',
        slug: 'wisdom',
        videoCount: 45,
      },
      views: 580000,
      publishedAt: '2024-12-25T10:00:00Z',
      createdAt: '2024-12-25T10:00:00Z',
      updatedAt: '2024-12-25T10:00:00Z',
      language: 'English',
    },
  ],

  playlists: [
    {
      id: 'playlist-1',
      name: 'Daily Meditation Series',
      description: 'A collection of guided meditations for daily practice',
      videos: [], // Will be populated from videos with playlistId
      thumbnail: '/images/playlists/daily-meditation.jpg',
      createdAt: '2025-01-01T10:00:00Z',
    },
    {
      id: 'playlist-2',
      name: 'Wisdom Talks by Gurudev',
      description: 'Inspiring wisdom talks and discourses',
      videos: [],
      thumbnail: '/images/playlists/wisdom-talks.jpg',
      createdAt: '2025-01-01T10:00:00Z',
    },
  ],

  speakers: [
    {
      id: 'speaker-1',
      name: 'Gurudev Sri Sri Ravi Shankar',
      bio: 'Founder of Art of Living Foundation, humanitarian, spiritual leader, and peace advocate',
      avatar: '/images/speakers/gurudev.jpg',
      role: 'Spiritual Leader',
    },
    {
      id: 'speaker-2',
      name: 'Dr. Priya Sharma',
      bio: 'Senior meditation teacher with 20+ years of experience',
      avatar: '/images/speakers/priya-sharma.jpg',
      role: 'Meditation Teacher',
    },
    {
      id: 'speaker-3',
      name: 'Rajesh Kumar',
      bio: 'Senior meditation teacher and life coach',
      avatar: '/images/speakers/rajesh-kumar.jpg',
      role: 'Meditation Teacher',
    },
    {
      id: 'speaker-4',
      name: 'Yoga Master Ananda',
      bio: 'Senior yoga teacher specializing in pranayama and asanas',
      avatar: '/images/speakers/ananda.jpg',
      role: 'Yoga Teacher',
    },
  ],
};
