/**
 * Enterprise search checklist — 501 items (IDs 1–501) with bucket + implementation tier.
 * Titles follow the canonical ordered checklist; infrastructure/ML items are tracked honestly.
 */

export type CapabilityBucket =
  | 'AI & ML'
  | 'Core Search'
  | 'UX & Interface'
  | 'Performance'
  | 'Security & Privacy'
  | 'Personalization'
  | 'Advanced Filtering'
  | 'Analytics & Insights'
  | 'Multi-Modal Search'
  | 'Developer & API';

export type ImplementationTier = 'in_app' | 'partial_client' | 'requires_infrastructure';

export type CapabilityEntry = {
  id: number;
  bucket: CapabilityBucket;
  /** Stable slug for i18n / analytics */
  slug: string;
  /** Display line — matches industry checklist ordering within bucket */
  title: string;
  tier: ImplementationTier;
};

const BUCKET_RANGES: { from: number; to: number; bucket: CapabilityBucket }[] = [
  { from: 1, to: 50, bucket: 'AI & ML' },
  { from: 51, to: 100, bucket: 'Core Search' },
  { from: 101, to: 150, bucket: 'UX & Interface' },
  { from: 151, to: 200, bucket: 'Performance' },
  { from: 201, to: 250, bucket: 'Security & Privacy' },
  { from: 251, to: 300, bucket: 'Personalization' },
  { from: 301, to: 350, bucket: 'Advanced Filtering' },
  { from: 351, to: 401, bucket: 'Analytics & Insights' },
  { from: 402, to: 451, bucket: 'Multi-Modal Search' },
  { from: 452, to: 501, bucket: 'Developer & API' },
];

function bucketForId(id: number): CapabilityBucket {
  for (const r of BUCKET_RANGES) {
    if (id >= r.from && id <= r.to) return r.bucket;
  }
  return 'Developer & API';
}

/** Ordered titles — line (id-1) = checklist item #id */
const TITLES: readonly string[] = [
  'AI-powered query understanding',
  'Semantic search',
  'Natural language search',
  'Intent detection',
  'Context-aware results',
  'Query auto-correction',
  'Smart typo fix',
  'Predictive search',
  'Conversational search',
  'Multi-turn search dialogue',
  'AI result ranking',
  'Neural ranking model',
  'BERT-based relevance',
  'GPT-integrated answers',
  'AI snippet generation',
  'Auto-summarized results',
  'Entity recognition in query',
  'Knowledge graph integration',
  'Zero-shot query expansion',
  'Few-shot result reranking',
  'AI-powered deduplication',
  'Sentiment-aware ranking',
  'Domain intent classification',
  'Query reformulation AI',
  'AI-based spam filtering',
  'Machine learning click signals',
  'Reinforcement learning ranking',
  'Personalized AI recommendations',
  'AI content freshness scoring',
  'AI-based trust scoring',
  'Deep learning image search',
  'AI video content indexing',
  'Speech-to-text search',
  'Text-to-speech results',
  'AI answer boxes',
  'AI-generated FAQs',
  'Automatic related queries AI',
  'AI-powered content clustering',
  'LLM-based result synthesis',
  'AI citation extraction',
  'Factual accuracy AI check',
  'AI bias detection in results',
  'Hallucination detection AI',
  'Contextual ads via AI',
  'AI-based trend detection',
  'Predictive query completion',
  'AI search assistant',
  'Multimodal AI search',
  'AI-based safe search',
  'AI relevance feedback learning',
  'Full-text search',
  'Boolean search operators',
  'Phrase search',
  'Wildcard search',
  'Fuzzy search',
  'Proximity search',
  'Field-specific search',
  'Exact match search',
  'Exclude terms (-) operator',
  'OR operator',
  'AND operator',
  'Nested queries',
  'Range queries',
  'Numeric range filter',
  'Date range filter',
  'Faceted search',
  'Multi-field search',
  'Weighted field search',
  'Synonym search',
  'Stemming support',
  'Lemmatization',
  'Stop word handling',
  'Tokenization engine',
  'Inverted index',
  'Forward index',
  'Positional index',
  'Real-time indexing',
  'Incremental indexing',
  'Distributed indexing',
  'Index sharding',
  'Index replication',
  'Index compression',
  'Index versioning',
  'Query parsing engine',
  'Query normalization',
  'Query tokenization',
  'Multi-language tokenizer',
  'Language auto-detection',
  'Character n-gram search',
  'Word n-gram search',
  'TF-IDF ranking',
  'BM25 ranking',
  'Hybrid ranking',
  'Sparse vector search',
  'Dense vector search',
  'ANN (Approximate Nearest Neighbor)',
  'HNSW indexing',
  'Flat index support',
  'IVF index support',
  'PQ compression index',
  'Instant search (as-you-type)',
  'Search suggestions dropdown',
  'Autocomplete',
  'Autofill previous queries',
  'Search history display',
  'Recent searches',
  'Trending searches display',
  'Popular queries widget',
  'Voice search input',
  'Image search input',
  'Camera search',
  'QR code search',
  'Barcode search',
  'Drag-and-drop file search',
  'Keyboard shortcut search',
  'Search bar anywhere',
  'Floating search widget',
  'Inline search results',
  'Sidebar search panel',
  'Modal search overlay',
  'Full-page results',
  'Infinite scroll results',
  'Pagination controls',
  'Results per page control',
  'Sort by relevance',
  'Sort by date',
  'Sort by popularity',
  'Sort by rating',
  'Sort by price',
  'Grid view results',
  'List view results',
  'Card view results',
  'Compact view results',
  'Rich snippet display',
  'Star ratings in results',
  'Price display in results',
  'Image thumbnails',
  'Video previews',
  'Preview pane',
  'Quick view hover',
  'Snippet highlighting',
  'Query term highlighting',
  'Bold matched keywords',
  'Color-coded result types',
  'Breadcrumb trails',
  'Result metadata display',
  'Share result button',
  'Copy result link',
  'Print results',
  'Export results to CSV',
  'Sub-100ms response time',
  'Edge caching',
  'CDN integration',
  'Query result caching',
  'Cache invalidation strategy',
  'Cache warming',
  'In-memory cache (Redis)',
  'Distributed cache',
  'Lazy loading results',
  'Prefetching next page',
  'Parallel query execution',
  'Asynchronous indexing',
  'Background re-ranking',
  'Load balancing',
  'Auto-scaling infrastructure',
  'Horizontal scaling',
  'Vertical scaling',
  'Microservices architecture',
  'gRPC communication',
  'HTTP/2 support',
  'HTTP/3 / QUIC support',
  'WebSocket live results',
  'Server-Sent Events (SSE)',
  'Connection pooling',
  'Query timeout management',
  'Circuit breaker pattern',
  'Rate limiting per user',
  'Rate limiting per IP',
  'Burst traffic handling',
  'Graceful degradation',
  'Fallback search mode',
  'Read replica support',
  'Write-ahead logging',
  'Compaction and merging',
  'Query queue management',
  'Priority queuing',
  'SLA-based routing',
  'Multi-region deployment',
  'Geo-distributed indexing',
  'Active-active replication',
  'Active-passive failover',
  'Zero-downtime deployment',
  'Rolling updates',
  'Blue-green deployment',
  'Canary releases',
  'Auto-healing infra',
  'Chaos engineering support',
  'Benchmark dashboards',
  'Latency percentile tracking',
  'Throughput monitoring',
  'End-to-end encryption',
  'HTTPS enforcement',
  'TLS 1.3 support',
  'OAuth 2.0 integration',
  'JWT authentication',
  'API key management',
  'Role-based access control',
  'Attribute-based access control',
  'Row-level security',
  'Column-level data masking',
  'Data anonymization',
  'GDPR compliance',
  'CCPA compliance',
  'PDPA compliance',
  'Privacy-by-design architecture',
  'Do Not Track support',
  'Zero-knowledge search',
  'Private search mode',
  'Search query encryption at rest',
  'Query log opt-out',
  'PII detection in queries',
  'IP address masking',
  'Anonymous search mode',
  'Content Security Policy (CSP)',
  'XSS protection',
  'SQL injection prevention',
  'SSRF protection',
  'CSRF token validation',
  'DDoS mitigation',
  'Bot detection',
  'CAPTCHA integration',
  'Fraud detection system',
  'Abuse detection',
  'Blacklist management',
  'Whitelist management',
  'Vulnerability scanning',
  'Penetration test support',
  'Audit logging',
  'Compliance reporting',
  'Data residency controls',
  'Right to erasure (delete)',
  'Data portability export',
  'Consent management',
  'Cookie consent integration',
  'Search result content moderation',
  'Legal hold support',
  'Sensitive content filtering',
  'Child-safe filtering',
  'Hate speech detection',
  'Malware URL filtering',
  'Phishing URL detection',
  'User profile-based ranking',
  'Behavioral personalization',
  'Search history personalization',
  'Click-through personalization',
  'Dwell time signals',
  'Purchase history signals',
  'Location-based personalization',
  'Time-of-day personalization',
  'Device-type personalization',
  'Language preference personalization',
  'Topic interest modeling',
  'Long-term preference learning',
  'Short-term context signals',
  'Collaborative filtering',
  'Content-based filtering',
  'Hybrid recommendation engine',
  'User segmentation',
  'A/B test personalization',
  'Personalized autocomplete',
  'Personalized filters',
  'Personalized result ordering',
  'Personalized snippets',
  'Personalized ads',
  'Saved searches',
  'Bookmarked results',
  'Follow topics',
  'Custom alerts',
  'Email digests of results',
  'Push notification results',
  'Personalized trending topics',
  'Interest graph',
  'Social graph integration',
  'Followed sources ranking',
  'Liked content signals',
  'Shared content signals',
  'Explicit feedback (thumbs up/down)',
  'Implicit feedback learning',
  'Diversity injection in results',
  'Serendipity injection',
  'Cold start personalization',
  'Cross-device sync',
  'Personalized date range default',
  'Personalized safe search level',
  'Personalized result language',
  'Personalized media type preference',
  'Personalized source trust',
  'Subscription-based content boost',
  'Premium content preference',
  'Location history personalization',
  'Opt-in/opt-out personalization',
  'Category filters',
  'Tag filters',
  'Source/domain filters',
  'File type filter (PDF, DOC...)',
  'Media type filter',
  'Language filter',
  'Country/region filter',
  'Publication date filter',
  'Author filter',
  'Price range filter',
  'Rating filter',
  'Availability filter',
  'Color filter (images)',
  'Size filter',
  'License filter (CC, commercial)',
  'Verified source filter',
  'Peer-reviewed filter',
  'News only filter',
  'Blog only filter',
  'Forum filter',
  'Government source filter',
  'Educational domain filter',
  'Video duration filter',
  'Image resolution filter',
  'Audio quality filter',
  'Read time filter',
  'Word count filter',
  'Domain authority filter',
  'Social shares filter',
  'Backlink count filter',
  'Age restriction filter',
  'Safe search level filter',
  'Open access filter',
  'Paywalled content filter',
  'Original content filter',
  'Translated content filter',
  'Updated recently filter',
  'Events filter',
  'Local results filter',
  'Product-only filter',
  'Review-only filter',
  'Job listing filter',
  'Research paper filter',
  'Patent filter',
  'Legal document filter',
  'Medical source filter',
  'Fact-checked filter',
  'Breaking news filter',
  'Sponsored filter toggle',
  'Custom filter builder',
  'Search analytics dashboard',
  'Query volume tracking',
  'Click-through rate (CTR) tracking',
  'Zero-result query tracking',
  'Popular query reports',
  'Query trend graphs',
  'User journey analytics',
  'Session replay',
  'Heatmap of results clicked',
  'Funnel analysis',
  'Conversion tracking',
  'Revenue attribution',
  'A/B test analytics',
  'Multivariate test analytics',
  'Cohort analysis',
  'Retention analysis',
  'Churn prediction',
  'Search satisfaction score',
  'Net Promoter Score (NPS)',
  'Average result position tracking',
  'Impression tracking',
  'Time-to-first-result metric',
  'Time-to-click metric',
  'Bounce rate from results',
  'Exit intent tracking',
  'Error query logging',
  'Typo analytics',
  'Synonym effectiveness tracking',
  'Filter usage analytics',
  'Facet engagement analytics',
  'Device breakdown analytics',
  'Browser analytics',
  'OS analytics',
  'Geographic analytics',
  'Language analytics',
  'Referrer analytics',
  'API usage analytics',
  'Quota usage reporting',
  'Alert thresholds',
  'Scheduled reports',
  'Export to BI tools',
  'Grafana integration',
  'Kibana integration',
  'DataDog integration',
  'Custom metrics API',
  'Real-time analytics',
  'Anomaly detection in traffic',
  'Forecast query volume',
  'Search ROI dashboard',
  'Competitive benchmark reports',
  'Text search',
  'Image search',
  'Video search',
  'Audio search',
  'Document search (PDF, DOCX)',
  'Spreadsheet search',
  'Presentation search',
  'Code search',
  '3D model search',
  'AR content search',
  'VR content search',
  'Map/location search',
  'Graph data search',
  'Structured data search',
  'Table search',
  'Chart/graph search',
  'Handwriting recognition search',
  'Sign language search',
  'Mathematical formula search',
  'Chemical formula search',
  'DNA sequence search',
  'Fingerprint search',
  'Face recognition search',
  'Object detection search',
  'Logo search',
  'Color palette search',
  'Pattern/texture search',
  'Sketch-to-image search',
  'Style-transfer search',
  'Caption-based image search',
  'OCR-powered document search',
  'EXIF metadata search',
  'Music/audio fingerprint search',
  'Podcast chapter search',
  'Social post search',
  'Email search integration',
  'Calendar event search',
  'Contact search',
  'Product search',
  'Recipe search',
  'Medicine search',
  'Legal case search',
  'Patent search',
  'Academic paper search',
  'Dataset search',
  'API endpoint search',
  'GitHub code search',
  'Stack Overflow search',
  'Arxiv paper search',
  'Wikipedia search',
  'REST API',
  'GraphQL API',
  'gRPC API',
  'WebSocket API',
  'Streaming search API',
  'Batch search API',
  'Search SDK (JS, Python, Go, Java)',
  'OpenAPI spec',
  'API versioning',
  'API documentation',
  'Interactive API playground',
  'Webhook support',
  'Event-driven search triggers',
  'Custom ranking API',
  'Custom synonym API',
  'Custom stopword API',
  'Index management API',
  'Document ingestion API',
  'Bulk indexing API',
  'Real-time update API',
  'Delta indexing API',
  'Geo-search API',
  'Facet API',
  'Spell check API',
  'Autocomplete API',
  'Suggestions API',
  'Analytics API',
  'User profile API',
  'Personalization API',
  'A/B test API',
  'Feature flag API',
  'Quota management API',
  'API rate limit headers',
  'API error codes',
  'API health endpoint',
  'API status page',
  'Sandbox environment',
  'Test mode',
  'Mock data generator',
  'CLI tool',
  'Admin dashboard API',
  'Backup API',
  'Restore API',
  'Migration tools',
  'Plugin system',
  'Custom middleware support',
  'Custom tokenizer plugin',
  'Custom ranker plugin',
  'Custom filter plugin',
  'Open-source connector library',
];

if (TITLES.length !== 501) {
  throw new Error(`searchCapabilityCatalog: expected 501 titles, got ${TITLES.length}`);
}

const SLUG_SAFE = /[^a-z0-9]+/g;

function slugify(id: number, title: string): string {
  const base = title
    .toLowerCase()
    .replace(SLUG_SAFE, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 48);
  return `${id}-${base || 'item'}`;
}

/** IDs implemented in this SPA (browser) today — expanded as features ship */
const IN_APP_IDS = new Set<number>([
  1, 4, 5, 6, 7, 8, 11, 19, 20, 21, 23, 26, 28, 37, 45, 46, 47, 50, 51, 52, 53, 54, 55, 57, 58, 59, 60, 61, 67, 69, 72, 84, 85, 86,
  101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 115, 120, 123, 124, 125, 126, 127, 133, 134, 137, 141, 142, 143, 144, 146, 147, 148,
  149, 150, 154, 159, 160, 177, 180, 248, 275, 276, 287, 288, 302, 303, 333, 352, 353, 355, 356, 402, 34,
]);

const PARTIAL_IDS = new Set<number>([
  2, 3, 9, 10, 12, 13, 14, 15, 16, 17, 18, 22, 24, 25, 27, 29, 30, 31, 32, 33, 35, 36, 38, 39, 40, 41, 42, 43, 44, 48, 49, 56, 62, 63,
  64, 65, 66, 68, 70, 71, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 111, 112,
  113, 114, 116, 117, 118, 119, 121, 122, 128, 129, 130, 131, 132, 135, 136, 138, 139, 140, 145, 151, 161, 162, 163, 164, 175, 176,
  178, 181, 201, 202, 203, 221, 224, 225, 226, 247, 301, 304, 351, 354, 357, 358, 377, 378, 397, 403, 440, 475, 476, 477, 501,
]);

function tierForId(id: number): ImplementationTier {
  if (IN_APP_IDS.has(id)) return 'in_app';
  if (PARTIAL_IDS.has(id)) return 'partial_client';
  return 'requires_infrastructure';
}

const ALL: CapabilityEntry[] = TITLES.map((title, index) => {
  const id = index + 1;
  return {
    id,
    bucket: bucketForId(id),
    slug: slugify(id, title),
    title,
    tier: tierForId(id),
  };
});

export const SEARCH_CHECKLIST_COUNT = 501 as const;

export const ALL_SEARCH_CAPABILITIES: readonly CapabilityEntry[] = ALL;

export function getSearchCapability(id: number): CapabilityEntry | undefined {
  if (id < 1 || id > 501) return undefined;
  return ALL[id - 1];
}

export function summarizeTiers(): { in_app: number; partial_client: number; requires_infrastructure: number } {
  let in_app = 0;
  let partial_client = 0;
  let requires_infrastructure = 0;
  for (const c of ALL) {
    if (c.tier === 'in_app') in_app += 1;
    else if (c.tier === 'partial_client') partial_client += 1;
    else requires_infrastructure += 1;
  }
  return { in_app, partial_client, requires_infrastructure };
}
