/**
 * Root Authentication System
 *
 * Handles root user authentication with secure password verification.
 * In production, this should be moved to a backend API.
 *
 * ⚠️ SECURITY NOTE: This is a frontend implementation for development.
 * In production, all authentication must happen on the backend server.
 */

import type { RootUser, RootSession, RootUserId } from './types';

// In production, this would be an API endpoint: '/api/root/users'
// For development, we'll use a hardcoded approach with a warning
const SESSION_STORAGE_KEY = 'root-session';
const SESSION_DURATION = 60 * 60 * 1000; // 1 hour

/**
 * Load root users
 *
 * ⚠️ SECURITY: In production, this MUST be a backend API call.
 * Root users should NEVER be exposed to the frontend.
 *
 * For development, we use a placeholder that simulates the backend.
 */
async function loadRootUsers(): Promise<RootUser[]> {
  // Root users must be loaded from a backend API.
  // Returns empty array — authentication will always fail without backend.
  return [];
}

/**
 * Verify password
 *
 * ⚠️ SECURITY: In production, this MUST be a backend API call.
 * Password verification must NEVER happen on the frontend.
 */
async function verifyPassword(username: string, password: string): Promise<{ valid: boolean; user?: RootUser }> {
  try {
    const response = await fetch('/api/root/verify', {
      method: 'POST',
      credentials: 'include',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ username, password }),
    });

    if (!response.ok) {
      return { valid: false };
    }

    const { user } = await response.json();
    return { valid: true, user };
  } catch (error) {
    console.error('[Root Auth] Backend verification failed:', error);
    return { valid: false };
  }
}

/**
 * Generate session token
 * In production, use JWT or similar secure token system
 */
function generateSessionToken(): string {
  // In production, this would be generated by the backend
  return `root_${Date.now()}_${Math.random().toString(36).substring(7)}`;
}

/**
 * Create root session
 */
function createSession(user: RootUser): RootSession {
  return {
    userId: user.id,
    username: user.username,
    token: generateSessionToken(),
    expiresAt: Date.now() + SESSION_DURATION,
    createdAt: Date.now(),
    ipAddress: typeof window !== 'undefined' ? 'client' : undefined,
    userAgent: typeof window !== 'undefined' ? navigator.userAgent : undefined,
  };
}

/**
 * Store session in sessionStorage
 */
function storeSession(session: RootSession): void {
  if (typeof window !== 'undefined') {
    sessionStorage.setItem(SESSION_STORAGE_KEY, JSON.stringify(session));
  }
}

/**
 * Get current session
 */
export function getSession(): RootSession | null {
  if (typeof window === 'undefined') return null;

  try {
    const stored = sessionStorage.getItem(SESSION_STORAGE_KEY);
    if (!stored) return null;

    const session: RootSession = JSON.parse(stored);

    // Check if session expired
    if (Date.now() > session.expiresAt) {
      clearSession();
      return null;
    }

    return session;
  } catch (error) {
    console.error('[Root Auth] Failed to parse session:', error);
    return null;
  }
}

/**
 * Clear session
 */
export function clearSession(): void {
  if (typeof window !== 'undefined') {
    sessionStorage.removeItem(SESSION_STORAGE_KEY);
  }
}

/**
 * Check if user is authenticated
 */
export function isAuthenticated(): boolean {
  return getSession() !== null;
}

/**
 * Authenticate root user
 *
 * ⚠️ SECURITY: In production, this MUST call a backend API
 */
export async function authenticateRootUser(
  username: string,
  password: string
): Promise<{ success: boolean; session?: RootSession; error?: string }> {
  try {
    // In production, this would be a single API call:
    // const response = await fetch('/api/root/authenticate', {
    //   method: 'POST',
    //   credentials: 'include',
    //   headers: { 'Content-Type': 'application/json' },
    //   body: JSON.stringify({ username, password }),
    // });
    // if (!response.ok) return { success: false, error: 'Invalid credentials' };
    // const { session } = await response.json();
    // storeSession(session);
    // return { success: true, session };

    // For development, verify password locally
    const result = await verifyPassword(username, password);

    if (!result.valid || !result.user) {
      // Silent failure - don't leak information
      return { success: false, error: 'Invalid credentials' };
    }

    // Create session
    const session = createSession(result.user);
    storeSession(session);

    // Log login (in production, this would be an API call)
    await logAuditAction({
      rootUserId: result.user.id,
      action: 'login',
      success: true,
      details: { username: result.user.username },
    });

    return { success: true, session };
  } catch (error) {
    console.error('[Root Auth] Authentication error:', error);
    return { success: false, error: 'Authentication failed' };
  }
}

/**
 * Logout root user
 */
export function logoutRootUser(): void {
  const session = getSession();
  if (session) {
    // Log logout (in production, this would be an API call)
    logAuditAction({
      rootUserId: session.userId,
      action: 'logout',
      success: true,
    }).catch(console.error);
  }
  clearSession();
}

/**
 * Get current root user ID
 */
export function getCurrentRootUserId(): RootUserId | null {
  const session = getSession();
  return session?.userId || null;
}

/**
 * Audit logging (placeholder - in production, this would be an API call)
 */
async function logAuditAction(_log: {
  rootUserId: RootUserId;
  action: string;
  success: boolean;
  details?: Record<string, unknown>;
}): Promise<void> {
  // Audit logging is intentionally silent on the client.
  // In production, this should send to a backend audit endpoint.
}
