// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const rawUrl = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const rawKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

/* createClient throws if URL/key are missing — that aborts the whole module graph
 * before React mounts, leaving the HTML “Loading…” skeleton up forever. */
const SUPABASE_URL =
  rawUrl?.trim() ||
  'https://placeholder.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = rawKey?.trim() || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.missing-env-placeholder';

export const isSupabaseConfigured = Boolean(rawUrl?.trim() && rawKey?.trim());

if (!isSupabaseConfigured && typeof console !== 'undefined') {
  console.warn(
    '[Supabase] VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY not set — using placeholder client so the app can load. DB calls will fail until env is configured.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

function safeLocalStorage(): Storage {
  try {
    const t = "__sb_ls_test__";
    localStorage.setItem(t, "1");
    localStorage.removeItem(t);
    return localStorage;
  } catch {
    const mem = new Map<string, string>();
    return {
      get length() {
        return mem.size;
      },
      clear() {
        mem.clear();
      },
      getItem(key: string) {
        return mem.get(key) ?? null;
      },
      key(i: number) {
        return [...mem.keys()][i] ?? null;
      },
      removeItem(key: string) {
        mem.delete(key);
      },
      setItem(key: string, value: string) {
        mem.set(key, value);
      },
    } as Storage;
  }
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: safeLocalStorage(),
    /* Avoid background refresh noise when env is not configured */
    persistSession: isSupabaseConfigured,
    autoRefreshToken: isSupabaseConfigured,
  },
});