/**
 * Testimonials - Data
 *
 * Content data for the Testimonials page.
 */

import type { TestimonialsPageData } from '../types';

export const testimonialsData: TestimonialsPageData = {
  featured: [
    {
      id: 'testimonial-1',
      quote: 'The Art of Living program transformed my life completely. I found peace I never knew existed.',
      fullStory: 'I came to the program struggling with anxiety and stress. Through the breathing techniques and meditation, I discovered a sense of calm and clarity that has stayed with me. My relationships improved, my work performance increased, and most importantly, I found inner peace.',
      author: {
        name: 'Sarah Mitchell',
        photo: '/images/testimonials/sarah-mitchell.jpg',
        location: 'New York',
        country: 'United States',
        countryCode: 'US',
        role: 'Marketing Executive',
        age: 34,
      },
      category: {
        id: 'life',
        name: 'Life',
        slug: 'life',
        description: 'Life transformation stories',
        testimonialCount: 45,
        icon: 'Heart',
      },
      type: 'text',
      date: '2024-12-15T10:00:00Z',
      featured: true,
      approved: true,
    },
    {
      id: 'testimonial-2',
      quote: 'After years of chronic pain, the yoga and meditation practices gave me my life back.',
      fullStory: 'I had been dealing with chronic back pain for over 10 years. Traditional treatments provided only temporary relief. The combination of yoga, pranayama, and meditation not only alleviated my pain but also gave me tools to manage stress, which was a major contributing factor.',
      author: {
        name: 'Michael Chen',
        photo: '/images/testimonials/michael-chen.jpg',
        location: 'San Francisco',
        country: 'United States',
        countryCode: 'US',
        role: 'Software Engineer',
        age: 42,
      },
      category: {
        id: 'health',
        name: 'Health',
        slug: 'health',
        description: 'Health and wellness transformations',
        testimonialCount: 38,
        icon: 'Activity',
      },
      type: 'text',
      date: '2024-12-10T10:00:00Z',
      featured: true,
      approved: true,
    },
  ],

  categories: [
    { id: 'all', name: 'All', slug: 'all', testimonialCount: 120 },
    { id: 'life', name: 'Life', slug: 'life', description: 'Life transformation', testimonialCount: 45, icon: 'Heart' },
    { id: 'health', name: 'Health', slug: 'health', description: 'Health & wellness', testimonialCount: 38, icon: 'Activity' },
    { id: 'youth', name: 'Youth', slug: 'youth', description: 'Youth programs', testimonialCount: 22, icon: 'GraduationCap' },
    { id: 'corporate', name: 'Corporate', slug: 'corporate', description: 'Corporate programs', testimonialCount: 15, icon: 'Briefcase' },
  ],

  testimonials: [
    {
      id: 'testimonial-1',
      quote: 'The Art of Living program transformed my life completely. I found peace I never knew existed.',
      fullStory: 'I came to the program struggling with anxiety and stress. Through the breathing techniques and meditation, I discovered a sense of calm and clarity that has stayed with me.',
      author: {
        name: 'Sarah Mitchell',
        photo: '/images/testimonials/sarah-mitchell.jpg',
        location: 'New York',
        country: 'United States',
        countryCode: 'US',
        role: 'Marketing Executive',
        age: 34,
      },
      category: {
        id: 'life',
        name: 'Life',
        slug: 'life',
        testimonialCount: 45,
      },
      type: 'text',
      date: '2024-12-15T10:00:00Z',
      featured: true,
      approved: true,
    },
    {
      id: 'testimonial-2',
      quote: 'After years of chronic pain, the yoga and meditation practices gave me my life back.',
      fullStory: 'I had been dealing with chronic back pain for over 10 years. The combination of yoga, pranayama, and meditation not only alleviated my pain but also gave me tools to manage stress.',
      author: {
        name: 'Michael Chen',
        photo: '/images/testimonials/michael-chen.jpg',
        location: 'San Francisco',
        country: 'United States',
        countryCode: 'US',
        role: 'Software Engineer',
        age: 42,
      },
      category: {
        id: 'health',
        name: 'Health',
        slug: 'health',
        testimonialCount: 38,
      },
      type: 'text',
      date: '2024-12-10T10:00:00Z',
      featured: true,
      approved: true,
    },
    {
      id: 'testimonial-3',
      quote: 'The youth program helped me discover my potential and build confidence I never had.',
      fullStory: 'As a teenager, I struggled with self-esteem and direction. The youth program not only taught me meditation but also helped me develop leadership skills and a sense of purpose.',
      author: {
        name: 'Priya Patel',
        photo: '/images/testimonials/priya-patel.jpg',
        location: 'Mumbai',
        country: 'India',
        countryCode: 'IN',
        role: 'Student',
        age: 19,
      },
      category: {
        id: 'youth',
        name: 'Youth',
        slug: 'youth',
        testimonialCount: 22,
      },
      type: 'video',
      videoUrl: 'https://www.youtube.com/watch?v=testimonial3',
      thumbnail: '/images/testimonials/priya-patel-video.jpg',
      date: '2024-12-05T10:00:00Z',
      approved: true,
    },
    {
      id: 'testimonial-4',
      quote: 'Our team\'s productivity and harmony improved dramatically after the corporate program.',
      fullStory: 'We implemented the corporate wellness program for our 200-person team. The results were remarkable - reduced stress, better communication, and increased productivity.',
      author: {
        name: 'David Thompson',
        photo: '/images/testimonials/david-thompson.jpg',
        location: 'London',
        country: 'United Kingdom',
        countryCode: 'GB',
        role: 'CEO',
        age: 48,
      },
      category: {
        id: 'corporate',
        name: 'Corporate',
        slug: 'corporate',
        testimonialCount: 15,
      },
      type: 'text',
      date: '2024-11-28T10:00:00Z',
      approved: true,
    },
    {
      id: 'testimonial-5',
      quote: 'Meditation became my anchor during the most challenging time of my life.',
      fullStory: 'After losing my job and going through a difficult divorce, I felt lost. The meditation practice I learned gave me strength, clarity, and hope to rebuild my life.',
      author: {
        name: 'Emma Wilson',
        photo: '/images/testimonials/emma-wilson.jpg',
        location: 'Toronto',
        country: 'Canada',
        countryCode: 'CA',
        role: 'Teacher',
        age: 36,
      },
      category: {
        id: 'life',
        name: 'Life',
        slug: 'life',
        testimonialCount: 45,
      },
      type: 'text',
      date: '2024-11-20T10:00:00Z',
      approved: true,
    },
    {
      id: 'testimonial-6',
      quote: 'The breathing techniques helped me overcome panic attacks that I had for years.',
      fullStory: 'I suffered from panic attacks for over 5 years. The Sudarshan Kriya breathing technique taught in the program was a game-changer. I now have tools to manage my anxiety effectively.',
      author: {
        name: 'James Anderson',
        photo: '/images/testimonials/james-anderson.jpg',
        location: 'Sydney',
        country: 'Australia',
        countryCode: 'AU',
        role: 'Designer',
        age: 29,
      },
      category: {
        id: 'health',
        name: 'Health',
        slug: 'health',
        testimonialCount: 38,
      },
      type: 'video',
      videoUrl: 'https://www.youtube.com/watch?v=testimonial6',
      thumbnail: '/images/testimonials/james-anderson-video.jpg',
      date: '2024-11-15T10:00:00Z',
      approved: true,
    },
  ],

  statistics: {
    total: 120,
    countries: 45,
    categories: 4,
  },
};
